apiVersion: v1
kind: Service
metadata:
  name: sistema-service
spec:
  selector:
    app: sistema-academico
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
    #nodePort: 31385 
    