apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-academico
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sistema-academico
  template:
    metadata:
      labels:
        app: sistema-academico
    spec:
      containers:
      - name: sistema-academico
        image: paulagalindo/sistema-academico:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/unir?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1234"
