- name: Verificar si Elasticsearch ya está instalado
  command: helm status elasticsearch -n {{ namespace }}
  register: elasticsearch_status
  ignore_errors: yes

- name: Instalar Elasticsearch
  shell: |
    helm upgrade --install elasticsearch elastic/elasticsearch \
      --namespace elk --create-namespace \
      -f /ansible/roles/elk/templates/values-elasticsearch.yaml
  environment:
    KUBECONFIG: /home/paula/.kube/config

- name: Verificar si Kibana ya está instalado
  command: helm status kibana -n {{ namespace }}
  register: kibana_status
  ignore_errors: yes

- name: Instalar Kibana
  shell: |
    helm upgrade --install kibana elastic/kibana \
      --namespace elk \
      -f /ansible/roles/elk/templates/values-kibana.yaml
  environment:
    KUBECONFIG: /home/paula/.kube/config

- name: Verificar si Filebeat ya está instalado
  command: helm status filebeat -n {{ namespace }}
  register: filebeat_status
  ignore_errors: yes

- name: Instalar Filebeat
  shell: |
    helm upgrade --install filebeat elastic/filebeat \
      --namespace elk \
      -f /ansible/roles/elk/templates/values-filebeat.yaml
  environment:
    KUBECONFIG: /home/paula/.kube/config
