- name: Despliegue del stack ELK en Kubernetes
  hosts: localhost
  vars:
    namespace: elk
  tasks:
    - name: Agregar repositorio Helm
      shell: helm repo add elastic https://helm.elastic.co && helm repo update

    - name: Crear namespace ELK
      shell: kubectl create namespace {{ namespace }}
      ignore_errors: yes

    - name: Instalar Elasticsearch
      shell: helm install elasticsearch elastic/elasticsearch --namespace {{ namespace }}

    - name: Instalar Kibana
      shell: helm install kibana elastic/kibana --namespace {{ namespace }}

    - name: Instalar Filebeat
      shell: |
        helm install filebeat elastic/filebeat --namespace {{ namespace }} \
        --set daemonset.enabled=true \
        --set filebeatConfig.filebeat.yml.output.elasticsearch.hosts='["http://elasticsearch-master:9200"]'

    - name: Crear servicio LoadBalancer para Kibana
      copy:
        dest: /tmp/kibana-service.yaml
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: kibana-lb
            namespace: {{ namespace }}
          spec:
            type: LoadBalancer
            ports:
              - port: 80
                targetPort: 5601
            selector:
              app: kibana
    - name: Aplicar servicio LoadBalancer
      shell: kubectl apply -f /tmp/kibana-service.yaml